"""empty message

Revision ID: 24d226a61135
Revises: f21d38b5807b
Create Date: 2020-07-20 21:55:25.135178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d226a61135'
down_revision = 'f21d38b5807b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('tags', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'tags')
    # ### end Alembic commands ###
