"""empty message

Revision ID: 84db833f2c6e
Revises: 24d226a61135
Create Date: 2020-08-17 18:57:37.040432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84db833f2c6e'
down_revision = '24d226a61135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('vk_active', sa.Boolean(), nullable=False),
    sa.Column('telegram_active', sa.Boolean(), nullable=False),
    sa.Column('vk_attachment', sa.String(length=120), nullable=True),
    sa.Column('telegram_attachment', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachment')
    # ### end Alembic commands ###
