"""empty message

Revision ID: d13367dc8ed1
Revises: 84db833f2c6e
Create Date: 2020-08-17 23:38:09.094218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13367dc8ed1'
down_revision = '84db833f2c6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'attachment', ['menu_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attachment', type_='unique')
    # ### end Alembic commands ###
