"""empty message

Revision ID: ed59d2846406
Revises: e68de889c2d2
Create Date: 2020-08-20 12:44:54.436999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed59d2846406'
down_revision = 'e68de889c2d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('attachment_active', sa.Boolean(), nullable=True))
    op.drop_column('attachment', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachment', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('attachment', 'attachment_active')
    # ### end Alembic commands ###
