"""empty message

Revision ID: f21d38b5807b
Revises: 
Create Date: 2020-07-18 05:54:23.692780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21d38b5807b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('text', sa.String(length=10000), nullable=True),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('value', sa.String(length=120), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inheritances',
    sa.Column('id_inher', sa.Integer(), nullable=False),
    sa.Column('menu_id_ancestor', sa.Integer(), nullable=True),
    sa.Column('menu_id_descendant', sa.Integer(), nullable=True),
    sa.Column('reversible', sa.Boolean(), nullable=False),
    sa.Column('added', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id_ancestor'], ['menu.id'], ),
    sa.ForeignKeyConstraint(['menu_id_descendant'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id_inher')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inheritances')
    op.drop_table('replace')
    op.drop_table('menu')
    # ### end Alembic commands ###
